import { spawnSync } from "node:child_process";
import { existsSync, mkdtempSync, readFileSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import { TokenError, tokensToCss } from "@/src/tokens/build";

type Dict = Record<string, any>;

const srgb = (hex: string, alpha?: number) => ({
  colorSpace: "srgb",
  components: [0, 0, 0],
  hex,
  ...(alpha === undefined ? {} : { alpha }),
});
const px = (value: number) => ({ value, unit: "px" });
const ms = (value: number) => ({ value, unit: "ms" });

// The smallest token file that tokensToCss accepts: one token in every required group.
function base(): Dict {
  return {
    color: {
      primitive: {
        "navy-900": { $type: "color", $value: srgb("#10233f") },
        "cream-50": { $type: "color", $value: srgb("#fdfbf5") },
      },
      day: { ink: { $type: "color", $value: "{color.primitive.navy-900}" } },
      night: { ink: { $type: "color", $value: "{color.primitive.cream-50}" } },
    },
    font: {
      family: {
        sans: { $type: "fontFamily", $value: ["Overpass", "system-ui", "sans-serif"] },
        mono: { $type: "fontFamily", $value: ["Overpass Mono", "ui-monospace", "monospace"] },
      },
    },
    space: { "4": { $type: "dimension", $value: px(4) } },
    radius: { card: { $type: "dimension", $value: px(16) } },
    elevation: {
      day: {
        small: {
          $type: "shadow",
          $value: [{ color: srgb("#10233f", 0.1), offsetX: px(0), offsetY: px(1), blur: px(0), spread: px(0) }],
        },
      },
      night: {
        small: {
          $type: "shadow",
          $value: [{ color: srgb("#000000", 0.2), offsetX: px(0), offsetY: px(1), blur: px(0), spread: px(0) }],
        },
      },
    },
    motion: {
      duration: { t1: { $type: "duration", $value: ms(120) } },
      easing: { ease: { $type: "cubicBezier", $value: [0.2, 0.7, 0.2, 1] } },
    },
  };
}

// The `--name: value;` lines of a piece of the generated CSS, as a map.
function declarations(css: string): Map<string, string> {
  const out = new Map<string, string>();
  for (const match of css.matchAll(/^\s*(--[a-z0-9-]+):\s*(.+);$/gm)) {
    out.set(match[1]!, match[2]!);
  }
  return out;
}

const DARK = "@media (prefers-color-scheme: dark) {";

// The day values: the first :root block, before the night block.
function vars(css: string): Map<string, string> {
  const dark = css.indexOf(DARK);
  return declarations(dark === -1 ? css : css.slice(0, dark));
}

// The night overrides: the declarations inside the prefers-color-scheme: dark block (empty when there is none).
function nightVars(css: string): Map<string, string> {
  const dark = css.indexOf(DARK);
  return dark === -1 ? new Map() : declarations(css.slice(dark));
}

describe("tokensToCss: structure", () => {
  it("rejects input that is not a JSON object", () => {
    expect(() => tokensToCss(null)).toThrow(TokenError);
    expect(() => tokensToCss([])).toThrow(TokenError);
    expect(() => tokensToCss("tokens")).toThrow(TokenError);
  });

  it("names a required group that is missing", () => {
    const tokens = base();
    delete tokens.color.day;
    expect(() => tokensToCss(tokens)).toThrow("color.day");
  });

  it("names a required group that has no tokens", () => {
    const tokens = base();
    tokens.color.day = {};
    expect(() => tokensToCss(tokens)).toThrow(/color\.day.*no tokens/);
  });

  it("emits the day :root block after a do-not-edit header, then the night block for a dark system setting", () => {
    const css = tokensToCss(base());
    expect(css.startsWith("/* Generated by scripts/build-tokens.ts")).toBe(true);
    expect(css.match(/^:root \{$/gm)).toHaveLength(1);
    expect(css.match(/@media/g)).toHaveLength(1);
    const dark = css.indexOf(DARK);
    expect(dark).toBeGreaterThan(css.indexOf(":root {"));
    expect(css.slice(dark)).toMatch(/^@media \(prefers-color-scheme: dark\) \{\n  :root \{\n[\s\S]*\n  \}\n\}\n$/);
    expect(css.trimEnd().endsWith("}")).toBe(true);
    expect(css.endsWith("\n")).toBe(true);
  });

  it("emits no night block when the token file has no night values", () => {
    const tokens = base();
    delete tokens.color.night;
    delete tokens.elevation.night;
    const css = tokensToCss(tokens);
    expect(css).not.toContain("@media");
    expect(css.match(/:root \{/g)).toHaveLength(1);
  });

  it("gives the same text for the same tokens", () => {
    expect(tokensToCss(base())).toBe(tokensToCss(base()));
  });
});

describe("tokensToCss: colors and references", () => {
  it("emits a --color variable per day color with the reference resolved", () => {
    expect(vars(tokensToCss(base())).get("--color-ink")).toBe("#10233f");
  });

  it("follows a chain of references", () => {
    const tokens = base();
    tokens.color.day.focus = { $type: "color", $value: "{color.day.ink}" };
    expect(vars(tokensToCss(tokens)).get("--color-focus")).toBe("#10233f");
  });

  it("leaves primitives out and keeps night colors out of the day block", () => {
    const css = tokensToCss(base());
    expect(css).not.toContain("navy-900");
    expect(css).not.toContain("cream-50");
    expect(css.slice(0, css.indexOf(DARK))).not.toContain("#fdfbf5");
  });

  it("writes a color with alpha below 1 as rgb with alpha, including fully clear", () => {
    const tokens = base();
    tokens.color.primitive["navy-a32"] = { $type: "color", $value: srgb("#10233f", 0.32) };
    tokens.color.primitive["mist-a0"] = { $type: "color", $value: srgb("#eef3f5", 0) };
    tokens.color.day.scrim = { $type: "color", $value: "{color.primitive.navy-a32}" };
    tokens.color.day.clear = { $type: "color", $value: "{color.primitive.mist-a0}" };
    tokens.color.day.solid = { $type: "color", $value: srgb("#FFFFFF", 1) };
    const out = vars(tokensToCss(tokens));
    expect(out.get("--color-scrim")).toBe("rgb(16 35 63 / 0.32)");
    expect(out.get("--color-clear")).toBe("rgb(238 243 245 / 0)");
    expect(out.get("--color-solid")).toBe("#ffffff");
  });

  it("builds the color from components when there is no hex", () => {
    const tokens = base();
    tokens.color.day.paper = { $type: "color", $value: { colorSpace: "srgb", components: [1, 0.5, 0] } };
    expect(vars(tokensToCss(tokens)).get("--color-paper")).toBe("#ff8000");
  });

  it("names the token and the reference when the reference does not exist", () => {
    const tokens = base();
    tokens.color.day.accent = { $type: "color", $value: "{color.primitive.amber-500}" };
    expect(() => tokensToCss(tokens)).toThrow(TokenError);
    expect(() => tokensToCss(tokens)).toThrow("color.day.accent refers to {color.primitive.amber-500}, which does not exist");
  });

  it("reports a circular reference instead of looping", () => {
    const tokens = base();
    tokens.color.day.a = { $type: "color", $value: "{color.day.b}" };
    tokens.color.day.b = { $type: "color", $value: "{color.day.a}" };
    expect(() => tokensToCss(tokens)).toThrow(/circular reference/);
  });

  it("rejects a color outside the srgb color space and names it", () => {
    const tokens = base();
    tokens.color.day.wide = { $type: "color", $value: { colorSpace: "display-p3", components: [1, 0, 0] } };
    expect(() => tokensToCss(tokens)).toThrow(/color\.day\.wide.*display-p3/);
  });

  it("rejects an alpha outside 0 to 1", () => {
    const tokens = base();
    tokens.color.day.bad = { $type: "color", $value: srgb("#000000", 1.5) };
    expect(() => tokensToCss(tokens)).toThrow(/color\.day\.bad/);
  });
});

describe("tokensToCss: the night theme", () => {
  it("overrides a day color with its night value under the same variable name", () => {
    const css = tokensToCss(base());
    expect(vars(css).get("--color-ink")).toBe("#10233f");
    expect(nightVars(css).get("--color-ink")).toBe("#fdfbf5");
  });

  it("does not override a day token that has no night value", () => {
    const tokens = base();
    tokens.color.day.scrim = { $type: "color", $value: srgb("#10233f", 0.32) };
    const css = tokensToCss(tokens);
    expect(vars(css).get("--color-scrim")).toBe("rgb(16 35 63 / 0.32)");
    expect(nightVars(css).has("--color-scrim")).toBe(false);
  });

  it("resolves a night reference to another night token", () => {
    const tokens = base();
    tokens.color.day.focus = { $type: "color", $value: "{color.day.ink}" };
    tokens.color.night.focus = { $type: "color", $value: "{color.night.ink}" };
    const css = tokensToCss(tokens);
    expect(vars(css).get("--color-focus")).toBe("#10233f");
    expect(nightVars(css).get("--color-focus")).toBe("#fdfbf5");
  });

  it("names the night token and the reference when the reference does not exist", () => {
    const tokens = base();
    tokens.color.night.ink.$value = "{color.primitive.bone-100}";
    expect(() => tokensToCss(tokens)).toThrow(TokenError);
    expect(() => tokensToCss(tokens)).toThrow("color.night.ink refers to {color.primitive.bone-100}, which does not exist");
  });

  it("names a night shadow whose color reference does not exist", () => {
    const tokens = base();
    tokens.elevation.night.small.$value = [
      { color: "{color.primitive.black-a20}", offsetX: px(0), offsetY: px(1), blur: px(0), spread: px(0) },
    ];
    expect(() => tokensToCss(tokens)).toThrow("elevation.night.small refers to {color.primitive.black-a20}, which does not exist");
  });

  it("rejects a night token that has no day token to override, and names it", () => {
    const tokens = base();
    tokens.color.night.glow = { $type: "color", $value: "{color.primitive.cream-50}" };
    expect(() => tokensToCss(tokens)).toThrow(TokenError);
    expect(() => tokensToCss(tokens)).toThrow(/color\.night\.glow .*--color-glow.*no day value/);
  });

  it("validates night values as strictly as day values", () => {
    const tokens = base();
    tokens.color.night.ink = { $type: "color", $value: srgb("#000000", 2) };
    expect(() => tokensToCss(tokens)).toThrow(/color\.night\.ink/);
  });
});

describe("tokensToCss: sizes, numbers and names", () => {
  it("emits space, size, radius, stroke and opacity with their prefixes", () => {
    const tokens = base();
    tokens.size = { gutter: { $type: "dimension", $value: px(16) } };
    tokens.stroke = { rule: { $type: "dimension", $value: px(1.5) } };
    tokens.opacity = { disabled: { $type: "number", $value: 0.45 } };
    const out = vars(tokensToCss(tokens));
    expect(out.get("--space-4")).toBe("4px");
    expect(out.get("--size-gutter")).toBe("16px");
    expect(out.get("--radius-card")).toBe("16px");
    expect(out.get("--stroke-rule")).toBe("1.5px");
    expect(out.get("--opacity-disabled")).toBe("0.45");
  });

  it("writes zero and negative dimensions with their unit", () => {
    const tokens = base();
    tokens.space.none = { $type: "dimension", $value: px(0) };
    tokens.space.pull = { $type: "dimension", $value: px(-18) };
    tokens.space.rem = { $type: "dimension", $value: { value: 1.25, unit: "rem" } };
    const out = vars(tokensToCss(tokens));
    expect(out.get("--space-none")).toBe("0px");
    expect(out.get("--space-pull")).toBe("-18px");
    expect(out.get("--space-rem")).toBe("1.25rem");
  });

  it("joins nested group names with hyphens", () => {
    const tokens = base();
    tokens.color.day.sky = { "1": { $type: "color", $value: "{color.primitive.navy-900}" } };
    expect(vars(tokensToCss(tokens)).get("--color-sky-1")).toBe("#10233f");
  });

  it("applies a $type declared on a group to the tokens inside it", () => {
    const tokens = base();
    tokens.size = { $type: "dimension", header: { $value: px(56) } };
    expect(vars(tokensToCss(tokens)).get("--size-header")).toBe("56px");
  });

  it("skips optional groups that are absent", () => {
    const css = tokensToCss(base());
    expect(css).not.toContain("--size-");
    expect(css).not.toContain("--stroke-");
    expect(css).not.toContain("--opacity-");
  });

  it("names the required space and radius groups when they are missing", () => {
    const noSpace = base();
    delete noSpace.space;
    expect(() => tokensToCss(noSpace)).toThrow("space");
    const noRadius = base();
    delete noRadius.radius;
    expect(() => tokensToCss(noRadius)).toThrow("radius");
  });

  it("rejects a token name that is not a lowercase CSS name and names the token", () => {
    const tokens = base();
    tokens.space["Big Gap"] = { $type: "dimension", $value: px(40) };
    expect(() => tokensToCss(tokens)).toThrow(/space\.Big Gap/);
  });

  it("rejects two tokens that would produce the same variable", () => {
    const tokens = base();
    tokens.color.day["sky-1"] = { $type: "color", $value: "{color.primitive.navy-900}" };
    tokens.color.day.sky = { "1": { $type: "color", $value: "{color.primitive.cream-50}" } };
    expect(() => tokensToCss(tokens)).toThrow(/--color-sky-1/);
  });

  it("names a token that has no $type", () => {
    const tokens = base();
    tokens.space.mystery = { $value: px(3) };
    expect(() => tokensToCss(tokens)).toThrow(/space\.mystery has no \$type/);
  });

  it("names a token with a type this build does not know", () => {
    const tokens = base();
    tokens.space.odd = { $type: "gradient", $value: [] };
    expect(() => tokensToCss(tokens)).toThrow(/space\.odd has unsupported type gradient/);
  });

  it("rejects a dimension without a numeric value or with an unknown unit", () => {
    const noNumber = base();
    noNumber.space.bad = { $type: "dimension", $value: { value: "4", unit: "px" } };
    expect(() => tokensToCss(noNumber)).toThrow(/space\.bad/);
    const badUnit = base();
    badUnit.space.bad = { $type: "dimension", $value: { value: 4, unit: "vw" } };
    expect(() => tokensToCss(badUnit)).toThrow(/space\.bad.*vw/);
  });

  it("rejects a number token that is not a finite number", () => {
    const tokens = base();
    tokens.opacity = { broken: { $type: "number", $value: "0.5" } };
    expect(() => tokensToCss(tokens)).toThrow(/opacity\.broken/);
  });
});

describe("tokensToCss: fonts and type roles", () => {
  const role = (overrides: Dict = {}) => ({
    $type: "typography",
    $value: {
      fontFamily: "{font.family.sans}",
      fontSize: px(25),
      fontWeight: "{font.weight.sans-semibold}",
      letterSpacing: px(-0.3),
      lineHeight: 1.28,
      ...overrides,
    },
  });

  function withTypography(roles: Dict): Dict {
    const tokens = base();
    tokens.font.weight = { "sans-semibold": { $type: "fontWeight", $value: 600 } };
    tokens.typography = roles;
    return tokens;
  }

  it("points --font-sans and --font-mono at the next/font variables, keeping the fallbacks", () => {
    const out = vars(tokensToCss(base()));
    expect(out.get("--font-sans")).toBe("var(--font-overpass), system-ui, sans-serif");
    expect(out.get("--font-mono")).toBe("var(--font-overpass-mono), ui-monospace, monospace");
  });

  it("writes any other family as a font stack, quoting names with spaces", () => {
    const tokens = base();
    tokens.font.family.serif = { $type: "fontFamily", $value: ["Source Serif 4", "Georgia", "serif"] };
    tokens.font.family.single = { $type: "fontFamily", $value: "Inter" };
    const out = vars(tokensToCss(tokens));
    expect(out.get("--font-serif")).toBe('"Source Serif 4", Georgia, serif');
    expect(out.get("--font-single")).toBe("Inter");
  });

  it("names the required font family group when it is missing", () => {
    const tokens = base();
    delete tokens.font;
    expect(() => tokensToCss(tokens)).toThrow("font.family");
  });

  it("rejects an empty font stack", () => {
    const tokens = base();
    tokens.font.family.sans.$value = [];
    expect(() => tokensToCss(tokens)).toThrow(/font\.family\.sans/);
  });

  it("emits font weights as --font-weight variables", () => {
    const tokens = base();
    tokens.font.weight = { "sans-extrabold": { $type: "fontWeight", $value: 800 }, "mono-bold": { $type: "fontWeight", $value: "bold" } };
    const out = vars(tokensToCss(tokens));
    expect(out.get("--font-weight-sans-extrabold")).toBe("800");
    expect(out.get("--font-weight-mono-bold")).toBe("bold");
  });

  it("rejects a font weight outside 1 to 1000", () => {
    const tokens = base();
    tokens.font.weight = { heavy: { $type: "fontWeight", $value: 1200 } };
    expect(() => tokensToCss(tokens)).toThrow(/font\.weight\.heavy/);
  });

  it("splits a type role into five variables with references resolved", () => {
    const out = vars(tokensToCss(withTypography({ "card-statement": role() })));
    expect(out.get("--type-card-statement-family")).toBe("var(--font-sans)");
    expect(out.get("--type-card-statement-size")).toBe("25px");
    expect(out.get("--type-card-statement-weight")).toBe("600");
    expect(out.get("--type-card-statement-line-height")).toBe("1.28");
    expect(out.get("--type-card-statement-letter-spacing")).toBe("-0.3px");
  });

  it("points a mono role at --font-mono", () => {
    const out = vars(tokensToCss(withTypography({ score: role({ fontFamily: "{font.family.mono}" }) })));
    expect(out.get("--type-score-family")).toBe("var(--font-mono)");
  });

  it("writes a role with a literal family and weight as they are", () => {
    const out = vars(tokensToCss(withTypography({ quote: role({ fontFamily: ["Georgia", "serif"], fontWeight: 400 }) })));
    expect(out.get("--type-quote-family")).toBe("Georgia, serif");
    expect(out.get("--type-quote-weight")).toBe("400");
  });

  it("accepts a line height given as a dimension", () => {
    const out = vars(tokensToCss(withTypography({ tight: role({ lineHeight: px(20) }) })));
    expect(out.get("--type-tight-line-height")).toBe("20px");
  });

  it("names the role and the field that is missing", () => {
    const value = role().$value as Dict;
    delete value.letterSpacing;
    expect(() => tokensToCss(withTypography({ stamp: { $type: "typography", $value: value } }))).toThrow(
      /typography\.stamp is missing letterSpacing/,
    );
  });

  it("names the role when its family reference does not exist", () => {
    expect(() => tokensToCss(withTypography({ logo: role({ fontFamily: "{font.family.display}" }) }))).toThrow(
      "typography.logo refers to {font.family.display}, which does not exist",
    );
  });
});

describe("tokensToCss: elevation and motion", () => {
  it("writes a day shadow as a CSS box-shadow list, layers in order", () => {
    const tokens = base();
    tokens.elevation.day.ticket = {
      $type: "shadow",
      $value: [
        { color: srgb("#10233f", 0.06), offsetX: px(0), offsetY: px(1), blur: px(0), spread: px(0) },
        { color: srgb("#10233f", 0.45), offsetX: px(0), offsetY: px(22), blur: px(36), spread: px(-18) },
      ],
    };
    expect(vars(tokensToCss(tokens)).get("--elevation-ticket")).toBe(
      "0px 1px 0px 0px rgb(16 35 63 / 0.06), 0px 22px 36px -18px rgb(16 35 63 / 0.45)",
    );
  });

  it("accepts a single shadow object, an inset layer and a color reference", () => {
    const tokens = base();
    tokens.elevation.day.well = {
      $type: "shadow",
      $value: { color: "{color.primitive.navy-900}", offsetX: px(0), offsetY: px(2), blur: px(4), spread: px(0), inset: true },
    };
    expect(vars(tokensToCss(tokens)).get("--elevation-well")).toBe("inset 0px 2px 4px 0px #10233f");
  });

  it("writes night elevation in the night block only, under the day variable name", () => {
    const css = tokensToCss(base());
    expect(vars(css).get("--elevation-small")).toBe("0px 1px 0px 0px rgb(16 35 63 / 0.1)");
    expect(nightVars(css).get("--elevation-small")).toBe("0px 1px 0px 0px rgb(0 0 0 / 0.2)");
    expect(css.slice(0, css.indexOf(DARK))).not.toContain("rgb(0 0 0");
  });

  it("names a shadow layer that is missing a field", () => {
    const tokens = base();
    tokens.elevation.day.small.$value = [{ color: srgb("#10233f"), offsetX: px(0), offsetY: px(1), spread: px(0) }];
    expect(() => tokensToCss(tokens)).toThrow(/elevation\.day\.small is missing blur/);
  });

  it("emits durations and easing curves", () => {
    const tokens = base();
    tokens.motion.duration.slow = { $type: "duration", $value: { value: 1.5, unit: "s" } };
    const out = vars(tokensToCss(tokens));
    expect(out.get("--duration-t1")).toBe("120ms");
    expect(out.get("--duration-slow")).toBe("1.5s");
    expect(out.get("--easing-ease")).toBe("cubic-bezier(0.2, 0.7, 0.2, 1)");
  });

  it("allows an overshooting curve but rejects x values outside 0 to 1 and wrong lengths", () => {
    const spring = base();
    spring.motion.easing.spring = { $type: "cubicBezier", $value: [0.34, 1.56, 0.64, 1] };
    expect(vars(tokensToCss(spring)).get("--easing-spring")).toBe("cubic-bezier(0.34, 1.56, 0.64, 1)");
    const badX = base();
    badX.motion.easing.bad = { $type: "cubicBezier", $value: [1.2, 0, 0.5, 1] };
    expect(() => tokensToCss(badX)).toThrow(/motion\.easing\.bad/);
    const short = base();
    short.motion.easing.short = { $type: "cubicBezier", $value: [0.2, 0.7, 0.2] };
    expect(() => tokensToCss(short)).toThrow(/motion\.easing\.short/);
  });

  it("names the required duration and easing groups when they are missing", () => {
    const noDuration = base();
    delete noDuration.motion.duration;
    expect(() => tokensToCss(noDuration)).toThrow("motion.duration");
    const noEasing = base();
    delete noEasing.motion.easing;
    expect(() => tokensToCss(noEasing)).toThrow("motion.easing");
    const noElevation = base();
    delete noElevation.elevation.day;
    expect(() => tokensToCss(noElevation)).toThrow("elevation.day");
  });

  it("writes springs and transitions as duration, curve and delay with references resolved", () => {
    const tokens = base();
    tokens.motion.duration.hold = { $type: "duration", $value: ms(60) };
    tokens.motion.spring = {
      snap: { $type: "transition", $value: { duration: "{motion.duration.t1}", delay: ms(0), timingFunction: "{motion.easing.ease}" } },
    };
    tokens.motion.transition = {
      travel: {
        $type: "transition",
        $value: { duration: ms(300), delay: "{motion.duration.hold}", timingFunction: [0, 0, 0.58, 1] },
      },
    };
    const out = vars(tokensToCss(tokens));
    expect(out.get("--spring-snap")).toBe("120ms cubic-bezier(0.2, 0.7, 0.2, 1) 0ms");
    expect(out.get("--transition-travel")).toBe("300ms cubic-bezier(0, 0, 0.58, 1) 60ms");
  });

  it("names a transition whose timing function reference does not exist", () => {
    const tokens = base();
    tokens.motion.transition = {
      press: { $type: "transition", $value: { duration: ms(120), delay: ms(0), timingFunction: "{motion.easing.bounce}" } },
    };
    expect(() => tokensToCss(tokens)).toThrow("motion.transition.press refers to {motion.easing.bounce}, which does not exist");
  });

  it("emits gesture tokens of mixed types", () => {
    const tokens = base();
    tokens.motion.gesture = {
      "commit-distance": { $type: "dimension", $value: px(90) },
      "rotation-divisor": { $type: "number", $value: 18 },
    };
    const out = vars(tokensToCss(tokens));
    expect(out.get("--gesture-commit-distance")).toBe("90px");
    expect(out.get("--gesture-rotation-divisor")).toBe("18");
  });
});

describe("tokensToCss: the real design/system/tokens.json", () => {
  const realTokens = JSON.parse(readFileSync(new URL("../../design/system/tokens.json", import.meta.url), "utf8"));
  const out = vars(tokensToCss(realTokens));

  // The names tasks 9 to 12 are written against. Values are not pinned: the design review may change them.
  const COLORS = [
    "sky-1", "sky-2", "sky-3", "sky-4", "surface", "surface-raised", "surface-sunk", "ink", "ink-muted", "rule",
    "accent", "on-accent", "true", "false", "correct", "wrong", "on-dark", "cloud", "scrim", "surface-sunk-clear",
    "focus", "focus-on-fill", "press",
  ];
  const TYPE_ROLES = [
    "logo", "screen-title", "step-title", "tagline", "card-statement", "card-name", "answer-value", "answer-label",
    "stamp", "button", "button-quiet", "button-back", "carrier-title", "carrier-label", "leg-code", "leg-name",
    "field-label", "field-value", "field-value-pass", "body", "body-small", "list-title", "list-statement",
    "option-title", "emphasis", "deck-code", "section-code", "score", "intent-stamp", "mono-data", "mono-data-strong",
    "mono-caption", "route-label", "sheet-title", "pass-line",
  ];
  const OTHERS = [
    "--font-sans", "--font-mono",
    "--font-weight-sans-semibold", "--font-weight-sans-extrabold", "--font-weight-mono-regular", "--font-weight-mono-semibold",
    ...["2", "4", "6", "8", "10", "12", "14", "16", "18", "20", "24"].map((n) => `--space-${n}`),
    ...[
      "safe-top", "safe-bottom", "gutter", "ticket-inset", "max-width", "touch-min", "header", "start-top-zone",
      "round-button", "pill", "pill-small", "actions", "carrier", "carrier-compact", "statement-min", "lower", "barcode",
      "notch", "card-notch", "card-stub", "card-stub-deck", "card-min", "card-min-deck", "card-min-off", "list-row",
      "sheet-bar", "sheet-overrun", "grab", "radio", "progress-track", "flight-path-height", "card-min-section",
      "card-min-class", "pass-line", "continue-icon", "foot-gap", "ready-offset",
    ].map((n) => `--size-${n}`),
    ...["card", "small", "pill", "pill-small", "tick"].map((n) => `--radius-${n}`),
    ...["rule", "perforation", "focus", "stamp", "radio", "quote", "icon"].map((n) => `--stroke-${n}`),
    "--opacity-cloud", "--opacity-disabled",
    ...["ticket", "small", "button", "press", "sheet"].map((n) => `--elevation-${n}`),
    ...[
      "t1", "t2", "t3", "stamp", "tear", "jolt", "stamp-timed", "leave-timed", "deal-timed", "hold-timed", "travel-hold",
      "travel", "step-exit-title", "step-exit", "step-enter", "step-enter-delay", "step-stagger", "top-exit",
      "top-enter-delay", "dash-out", "dash-in", "reduced-out", "reduced-in", "board", "strike",
    ].map((n) => `--duration-${n}`),
    ...["ease", "spring", "fall", "ease-in", "ease-out"].map((n) => `--easing-${n}`),
    ...["snap", "land", "land-fast"].map((n) => `--spring-${n}`),
    ...[
      "press", "answer-row", "tear", "stamp", "jolt", "sheet-open", "sheet-close", "disclosure", "travel", "step-enter",
      "step-exit", "timed-leave", "timed-deal", "pass-resize", "pass-board",
    ].map((n) => `--transition-${n}`),
    ...["commit-distance", "intent-distance", "rotation-divisor", "stub-pull", "intent-opacity-gain"].map((n) => `--gesture-${n}`),
  ];

  it("emits every day color the UI uses", () => {
    for (const name of COLORS) expect(out.has(`--color-${name}`), `--color-${name}`).toBe(true);
  });

  it("emits exactly the day colors, no primitives or night colors", () => {
    const colors = [...out.keys()].filter((name) => name.startsWith("--color-"));
    expect(colors).toHaveLength(Object.keys(realTokens.color.day).filter((key) => !key.startsWith("$")).length);
  });

  it("emits five variables for every type role", () => {
    for (const role of TYPE_ROLES) {
      for (const suffix of ["family", "size", "weight", "line-height", "letter-spacing"]) {
        expect(out.has(`--type-${role}-${suffix}`), `--type-${role}-${suffix}`).toBe(true);
      }
    }
  });

  it("emits the font, spacing, size, radius, stroke, opacity, elevation and motion variables", () => {
    for (const name of OTHERS) expect(out.has(name), name).toBe(true);
  });

  it("points the font families at the next/font variables", () => {
    expect(out.get("--font-sans")).toMatch(/^var\(--font-overpass\), /);
    expect(out.get("--font-mono")).toMatch(/^var\(--font-overpass-mono\), /);
  });

  it("overrides every day color and shadow that has a night value, and keeps scrim and the sheet shadow from day", () => {
    const night = nightVars(tokensToCss(realTokens));
    const keys = (group: Record<string, unknown>) => Object.keys(group).filter((key) => !key.startsWith("$"));
    expect([...night.keys()].sort()).toEqual(
      [...keys(realTokens.color.night).map((k) => `--color-${k}`), ...keys(realTokens.elevation.night).map((k) => `--elevation-${k}`)].sort(),
    );
    for (const name of night.keys()) expect(out.has(name), name).toBe(true);
    for (const name of COLORS.filter((n) => n !== "scrim")) expect(night.has(`--color-${name}`), `--color-${name}`).toBe(true);
    for (const name of ["ticket", "small", "button", "press"]) expect(night.has(`--elevation-${name}`), `--elevation-${name}`).toBe(true);
    expect(night.has("--color-scrim")).toBe(false);
    expect(night.has("--elevation-sheet")).toBe(false);
  });

  it("leaves no unresolved reference or broken value in the output", () => {
    for (const [name, value] of [...out, ...nightVars(tokensToCss(realTokens))]) {
      expect(value, name).not.toMatch(/[{}]|undefined|NaN|\[object/);
      expect(value.trim(), name).not.toBe("");
    }
  });
});

describe("scripts/build-tokens.ts", () => {
  const root = fileURLToPath(new URL("../../", import.meta.url));
  const tsx = join(root, "node_modules/tsx/dist/cli.mjs");

  function run(source: string, target: string) {
    return spawnSync(process.execPath, [tsx, "scripts/build-tokens.ts", source, target], { cwd: root, encoding: "utf8" });
  }

  function workspace(): string {
    return mkdtempSync(join(tmpdir(), "truthy-tokens-"));
  }

  it("writes the CSS for a valid token file and reports how many variables", () => {
    const dir = workspace();
    writeFileSync(join(dir, "tokens.json"), JSON.stringify(base()));
    const result = run(join(dir, "tokens.json"), join(dir, "tokens.css"));
    expect(result.status).toBe(0);
    expect(result.stdout).toMatch(/Wrote .*tokens\.css \(\d+ variables\)/);
    expect(readFileSync(join(dir, "tokens.css"), "utf8")).toBe(tokensToCss(base()));
  });

  it("exits non-zero and names the token when a reference is broken", () => {
    const dir = workspace();
    const tokens = base();
    tokens.color.day.ink.$value = "{color.primitive.gone}";
    writeFileSync(join(dir, "tokens.json"), JSON.stringify(tokens));
    const result = run(join(dir, "tokens.json"), join(dir, "tokens.css"));
    expect(result.status).toBe(1);
    expect(result.stderr).toContain("color.day.ink refers to {color.primitive.gone}");
    expect(existsSync(join(dir, "tokens.css"))).toBe(false);
  });

  it("exits non-zero and names the night token when its reference is broken", () => {
    const dir = workspace();
    const tokens = base();
    tokens.color.night.ink.$value = "{color.primitive.gone}";
    writeFileSync(join(dir, "tokens.json"), JSON.stringify(tokens));
    const result = run(join(dir, "tokens.json"), join(dir, "tokens.css"));
    expect(result.status).toBe(1);
    expect(result.stderr).toContain("color.night.ink refers to {color.primitive.gone}");
    expect(existsSync(join(dir, "tokens.css"))).toBe(false);
  });

  it("keeps the previous CSS and names the file when tokens.json is not valid JSON", () => {
    const dir = workspace();
    writeFileSync(join(dir, "tokens.json"), '{ "color": { "day": { }, }');
    writeFileSync(join(dir, "tokens.css"), "/* previous */\n");
    const result = run(join(dir, "tokens.json"), join(dir, "tokens.css"));
    expect(result.status).toBe(1);
    expect(result.stderr).toContain(`build:tokens failed for ${join(dir, "tokens.json")}`);
    expect(readFileSync(join(dir, "tokens.css"), "utf8")).toBe("/* previous */\n");
  });
});

describe("tokensToCss: awkward references", () => {
  it("rejects text that looks like a reference but is not exactly one", () => {
    for (const bad of ["{color.primitive.navy-900", "{ color.primitive.navy-900 }", "{color.primitive.navy-900} 50%"]) {
      const tokens = base();
      tokens.font.family.sans.$value = bad;
      expect(() => tokensToCss(tokens), bad).toThrow(/font\.family\.sans has a malformed reference/);
    }
  });

  it("says so when a reference points at a group instead of a token", () => {
    const tokens = base();
    tokens.color.day.ink.$value = "{color.primitive}";
    expect(() => tokensToCss(tokens)).toThrow("color.day.ink refers to {color.primitive}, which is a group, not a token");
  });
});
