import { describe, expect, it } from "vitest";
import { TokenError, tokensToCss } from "@/src/tokens/build";

type Dict = Record<string, any>;

const srgb = (hex: string, alpha?: number) => ({
  colorSpace: "srgb",
  components: [0, 0, 0],
  hex,
  ...(alpha === undefined ? {} : { alpha }),
});
const px = (value: number) => ({ value, unit: "px" });
const ms = (value: number) => ({ value, unit: "ms" });

// The smallest token file that tokensToCss accepts: one token in every required group.
function base(): Dict {
  return {
    color: {
      primitive: {
        "navy-900": { $type: "color", $value: srgb("#10233f") },
        "cream-50": { $type: "color", $value: srgb("#fdfbf5") },
      },
      day: { ink: { $type: "color", $value: "{color.primitive.navy-900}" } },
      night: { ink: { $type: "color", $value: "{color.primitive.cream-50}" } },
    },
    font: {
      family: {
        sans: { $type: "fontFamily", $value: ["Overpass", "system-ui", "sans-serif"] },
        mono: { $type: "fontFamily", $value: ["Overpass Mono", "ui-monospace", "monospace"] },
      },
    },
    space: { "4": { $type: "dimension", $value: px(4) } },
    radius: { card: { $type: "dimension", $value: px(16) } },
    elevation: {
      day: {
        small: {
          $type: "shadow",
          $value: [{ color: srgb("#10233f", 0.1), offsetX: px(0), offsetY: px(1), blur: px(0), spread: px(0) }],
        },
      },
      night: {
        small: {
          $type: "shadow",
          $value: [{ color: srgb("#000000", 0.2), offsetX: px(0), offsetY: px(1), blur: px(0), spread: px(0) }],
        },
      },
    },
    motion: {
      duration: { t1: { $type: "duration", $value: ms(120) } },
      easing: { ease: { $type: "cubicBezier", $value: [0.2, 0.7, 0.2, 1] } },
    },
  };
}

// Reads the `--name: value;` lines of the generated CSS into a map.
function vars(css: string): Map<string, string> {
  const out = new Map<string, string>();
  for (const match of css.matchAll(/^\s*(--[a-z0-9-]+):\s*(.+);$/gm)) {
    out.set(match[1]!, match[2]!);
  }
  return out;
}

describe("tokensToCss: structure", () => {
  it("rejects input that is not a JSON object", () => {
    expect(() => tokensToCss(null)).toThrow(TokenError);
    expect(() => tokensToCss([])).toThrow(TokenError);
    expect(() => tokensToCss("tokens")).toThrow(TokenError);
  });

  it("names a required group that is missing", () => {
    const tokens = base();
    delete tokens.color.day;
    expect(() => tokensToCss(tokens)).toThrow("color.day");
  });

  it("names a required group that has no tokens", () => {
    const tokens = base();
    tokens.color.day = {};
    expect(() => tokensToCss(tokens)).toThrow(/color\.day.*no tokens/);
  });

  it("emits one :root block after a do-not-edit header", () => {
    const css = tokensToCss(base());
    expect(css.startsWith("/* Generated by scripts/build-tokens.ts")).toBe(true);
    expect(css.match(/:root \{/g)).toHaveLength(1);
    expect(css.trimEnd().endsWith("}")).toBe(true);
    expect(css.endsWith("\n")).toBe(true);
  });

  it("gives the same text for the same tokens", () => {
    expect(tokensToCss(base())).toBe(tokensToCss(base()));
  });
});

describe("tokensToCss: colors and references", () => {
  it("emits a --color variable per day color with the reference resolved", () => {
    expect(vars(tokensToCss(base())).get("--color-ink")).toBe("#10233f");
  });

  it("follows a chain of references", () => {
    const tokens = base();
    tokens.color.day.focus = { $type: "color", $value: "{color.day.ink}" };
    expect(vars(tokensToCss(tokens)).get("--color-focus")).toBe("#10233f");
  });

  it("leaves primitives and night colors out", () => {
    const css = tokensToCss(base());
    expect(css).not.toContain("navy-900");
    expect(css).not.toContain("#fdfbf5");
    expect(css).not.toContain("night");
  });

  it("writes a color with alpha below 1 as rgb with alpha, including fully clear", () => {
    const tokens = base();
    tokens.color.primitive["navy-a32"] = { $type: "color", $value: srgb("#10233f", 0.32) };
    tokens.color.primitive["mist-a0"] = { $type: "color", $value: srgb("#eef3f5", 0) };
    tokens.color.day.scrim = { $type: "color", $value: "{color.primitive.navy-a32}" };
    tokens.color.day.clear = { $type: "color", $value: "{color.primitive.mist-a0}" };
    tokens.color.day.solid = { $type: "color", $value: srgb("#FFFFFF", 1) };
    const out = vars(tokensToCss(tokens));
    expect(out.get("--color-scrim")).toBe("rgb(16 35 63 / 0.32)");
    expect(out.get("--color-clear")).toBe("rgb(238 243 245 / 0)");
    expect(out.get("--color-solid")).toBe("#ffffff");
  });

  it("builds the color from components when there is no hex", () => {
    const tokens = base();
    tokens.color.day.paper = { $type: "color", $value: { colorSpace: "srgb", components: [1, 0.5, 0] } };
    expect(vars(tokensToCss(tokens)).get("--color-paper")).toBe("#ff8000");
  });

  it("names the token and the reference when the reference does not exist", () => {
    const tokens = base();
    tokens.color.day.accent = { $type: "color", $value: "{color.primitive.amber-500}" };
    expect(() => tokensToCss(tokens)).toThrow(TokenError);
    expect(() => tokensToCss(tokens)).toThrow("color.day.accent refers to {color.primitive.amber-500}, which does not exist");
  });

  it("reports a circular reference instead of looping", () => {
    const tokens = base();
    tokens.color.day.a = { $type: "color", $value: "{color.day.b}" };
    tokens.color.day.b = { $type: "color", $value: "{color.day.a}" };
    expect(() => tokensToCss(tokens)).toThrow(/circular reference/);
  });

  it("rejects a color outside the srgb color space and names it", () => {
    const tokens = base();
    tokens.color.day.wide = { $type: "color", $value: { colorSpace: "display-p3", components: [1, 0, 0] } };
    expect(() => tokensToCss(tokens)).toThrow(/color\.day\.wide.*display-p3/);
  });

  it("rejects an alpha outside 0 to 1", () => {
    const tokens = base();
    tokens.color.day.bad = { $type: "color", $value: srgb("#000000", 1.5) };
    expect(() => tokensToCss(tokens)).toThrow(/color\.day\.bad/);
  });
});
