import { describe, expect, it } from "vitest";
import { TokenError, tokensToCss } from "@/src/tokens/build";

type Dict = Record<string, any>;

const srgb = (hex: string, alpha?: number) => ({
  colorSpace: "srgb",
  components: [0, 0, 0],
  hex,
  ...(alpha === undefined ? {} : { alpha }),
});
const px = (value: number) => ({ value, unit: "px" });
const ms = (value: number) => ({ value, unit: "ms" });

// The smallest token file that tokensToCss accepts: one token in every required group.
function base(): Dict {
  return {
    color: {
      primitive: {
        "navy-900": { $type: "color", $value: srgb("#10233f") },
        "cream-50": { $type: "color", $value: srgb("#fdfbf5") },
      },
      day: { ink: { $type: "color", $value: "{color.primitive.navy-900}" } },
      night: { ink: { $type: "color", $value: "{color.primitive.cream-50}" } },
    },
    font: {
      family: {
        sans: { $type: "fontFamily", $value: ["Overpass", "system-ui", "sans-serif"] },
        mono: { $type: "fontFamily", $value: ["Overpass Mono", "ui-monospace", "monospace"] },
      },
    },
    space: { "4": { $type: "dimension", $value: px(4) } },
    radius: { card: { $type: "dimension", $value: px(16) } },
    elevation: {
      day: {
        small: {
          $type: "shadow",
          $value: [{ color: srgb("#10233f", 0.1), offsetX: px(0), offsetY: px(1), blur: px(0), spread: px(0) }],
        },
      },
      night: {
        small: {
          $type: "shadow",
          $value: [{ color: srgb("#000000", 0.2), offsetX: px(0), offsetY: px(1), blur: px(0), spread: px(0) }],
        },
      },
    },
    motion: {
      duration: { t1: { $type: "duration", $value: ms(120) } },
      easing: { ease: { $type: "cubicBezier", $value: [0.2, 0.7, 0.2, 1] } },
    },
  };
}

// Reads the `--name: value;` lines of the generated CSS into a map.
function vars(css: string): Map<string, string> {
  const out = new Map<string, string>();
  for (const match of css.matchAll(/^\s*(--[a-z0-9-]+):\s*(.+);$/gm)) {
    out.set(match[1]!, match[2]!);
  }
  return out;
}

describe("tokensToCss: structure", () => {
  it("rejects input that is not a JSON object", () => {
    expect(() => tokensToCss(null)).toThrow(TokenError);
    expect(() => tokensToCss([])).toThrow(TokenError);
    expect(() => tokensToCss("tokens")).toThrow(TokenError);
  });

  it("names a required group that is missing", () => {
    const tokens = base();
    delete tokens.color.day;
    expect(() => tokensToCss(tokens)).toThrow("color.day");
  });

  it("names a required group that has no tokens", () => {
    const tokens = base();
    tokens.color.day = {};
    expect(() => tokensToCss(tokens)).toThrow(/color\.day.*no tokens/);
  });

  it("emits one :root block after a do-not-edit header", () => {
    const css = tokensToCss(base());
    expect(css.startsWith("/* Generated by scripts/build-tokens.ts")).toBe(true);
    expect(css.match(/:root \{/g)).toHaveLength(1);
    expect(css.trimEnd().endsWith("}")).toBe(true);
    expect(css.endsWith("\n")).toBe(true);
  });

  it("gives the same text for the same tokens", () => {
    expect(tokensToCss(base())).toBe(tokensToCss(base()));
  });
});

describe("tokensToCss: colors and references", () => {
  it("emits a --color variable per day color with the reference resolved", () => {
    expect(vars(tokensToCss(base())).get("--color-ink")).toBe("#10233f");
  });

  it("follows a chain of references", () => {
    const tokens = base();
    tokens.color.day.focus = { $type: "color", $value: "{color.day.ink}" };
    expect(vars(tokensToCss(tokens)).get("--color-focus")).toBe("#10233f");
  });

  it("leaves primitives and night colors out", () => {
    const css = tokensToCss(base());
    expect(css).not.toContain("navy-900");
    expect(css).not.toContain("#fdfbf5");
    expect(css).not.toContain("night");
  });

  it("writes a color with alpha below 1 as rgb with alpha, including fully clear", () => {
    const tokens = base();
    tokens.color.primitive["navy-a32"] = { $type: "color", $value: srgb("#10233f", 0.32) };
    tokens.color.primitive["mist-a0"] = { $type: "color", $value: srgb("#eef3f5", 0) };
    tokens.color.day.scrim = { $type: "color", $value: "{color.primitive.navy-a32}" };
    tokens.color.day.clear = { $type: "color", $value: "{color.primitive.mist-a0}" };
    tokens.color.day.solid = { $type: "color", $value: srgb("#FFFFFF", 1) };
    const out = vars(tokensToCss(tokens));
    expect(out.get("--color-scrim")).toBe("rgb(16 35 63 / 0.32)");
    expect(out.get("--color-clear")).toBe("rgb(238 243 245 / 0)");
    expect(out.get("--color-solid")).toBe("#ffffff");
  });

  it("builds the color from components when there is no hex", () => {
    const tokens = base();
    tokens.color.day.paper = { $type: "color", $value: { colorSpace: "srgb", components: [1, 0.5, 0] } };
    expect(vars(tokensToCss(tokens)).get("--color-paper")).toBe("#ff8000");
  });

  it("names the token and the reference when the reference does not exist", () => {
    const tokens = base();
    tokens.color.day.accent = { $type: "color", $value: "{color.primitive.amber-500}" };
    expect(() => tokensToCss(tokens)).toThrow(TokenError);
    expect(() => tokensToCss(tokens)).toThrow("color.day.accent refers to {color.primitive.amber-500}, which does not exist");
  });

  it("reports a circular reference instead of looping", () => {
    const tokens = base();
    tokens.color.day.a = { $type: "color", $value: "{color.day.b}" };
    tokens.color.day.b = { $type: "color", $value: "{color.day.a}" };
    expect(() => tokensToCss(tokens)).toThrow(/circular reference/);
  });

  it("rejects a color outside the srgb color space and names it", () => {
    const tokens = base();
    tokens.color.day.wide = { $type: "color", $value: { colorSpace: "display-p3", components: [1, 0, 0] } };
    expect(() => tokensToCss(tokens)).toThrow(/color\.day\.wide.*display-p3/);
  });

  it("rejects an alpha outside 0 to 1", () => {
    const tokens = base();
    tokens.color.day.bad = { $type: "color", $value: srgb("#000000", 1.5) };
    expect(() => tokensToCss(tokens)).toThrow(/color\.day\.bad/);
  });
});

describe("tokensToCss: sizes, numbers and names", () => {
  it("emits space, size, radius, stroke and opacity with their prefixes", () => {
    const tokens = base();
    tokens.size = { gutter: { $type: "dimension", $value: px(16) } };
    tokens.stroke = { rule: { $type: "dimension", $value: px(1.5) } };
    tokens.opacity = { disabled: { $type: "number", $value: 0.45 } };
    const out = vars(tokensToCss(tokens));
    expect(out.get("--space-4")).toBe("4px");
    expect(out.get("--size-gutter")).toBe("16px");
    expect(out.get("--radius-card")).toBe("16px");
    expect(out.get("--stroke-rule")).toBe("1.5px");
    expect(out.get("--opacity-disabled")).toBe("0.45");
  });

  it("writes zero and negative dimensions with their unit", () => {
    const tokens = base();
    tokens.space.none = { $type: "dimension", $value: px(0) };
    tokens.space.pull = { $type: "dimension", $value: px(-18) };
    tokens.space.rem = { $type: "dimension", $value: { value: 1.25, unit: "rem" } };
    const out = vars(tokensToCss(tokens));
    expect(out.get("--space-none")).toBe("0px");
    expect(out.get("--space-pull")).toBe("-18px");
    expect(out.get("--space-rem")).toBe("1.25rem");
  });

  it("joins nested group names with hyphens", () => {
    const tokens = base();
    tokens.color.day.sky = { "1": { $type: "color", $value: "{color.primitive.navy-900}" } };
    expect(vars(tokensToCss(tokens)).get("--color-sky-1")).toBe("#10233f");
  });

  it("applies a $type declared on a group to the tokens inside it", () => {
    const tokens = base();
    tokens.size = { $type: "dimension", header: { $value: px(56) } };
    expect(vars(tokensToCss(tokens)).get("--size-header")).toBe("56px");
  });

  it("skips optional groups that are absent", () => {
    const css = tokensToCss(base());
    expect(css).not.toContain("--size-");
    expect(css).not.toContain("--stroke-");
    expect(css).not.toContain("--opacity-");
  });

  it("names the required space and radius groups when they are missing", () => {
    const noSpace = base();
    delete noSpace.space;
    expect(() => tokensToCss(noSpace)).toThrow("space");
    const noRadius = base();
    delete noRadius.radius;
    expect(() => tokensToCss(noRadius)).toThrow("radius");
  });

  it("rejects a token name that is not a lowercase CSS name and names the token", () => {
    const tokens = base();
    tokens.space["Big Gap"] = { $type: "dimension", $value: px(40) };
    expect(() => tokensToCss(tokens)).toThrow(/space\.Big Gap/);
  });

  it("rejects two tokens that would produce the same variable", () => {
    const tokens = base();
    tokens.color.day["sky-1"] = { $type: "color", $value: "{color.primitive.navy-900}" };
    tokens.color.day.sky = { "1": { $type: "color", $value: "{color.primitive.cream-50}" } };
    expect(() => tokensToCss(tokens)).toThrow(/--color-sky-1/);
  });

  it("names a token that has no $type", () => {
    const tokens = base();
    tokens.space.mystery = { $value: px(3) };
    expect(() => tokensToCss(tokens)).toThrow(/space\.mystery has no \$type/);
  });

  it("names a token with a type this build does not know", () => {
    const tokens = base();
    tokens.space.odd = { $type: "gradient", $value: [] };
    expect(() => tokensToCss(tokens)).toThrow(/space\.odd has unsupported type gradient/);
  });

  it("rejects a dimension without a numeric value or with an unknown unit", () => {
    const noNumber = base();
    noNumber.space.bad = { $type: "dimension", $value: { value: "4", unit: "px" } };
    expect(() => tokensToCss(noNumber)).toThrow(/space\.bad/);
    const badUnit = base();
    badUnit.space.bad = { $type: "dimension", $value: { value: 4, unit: "vw" } };
    expect(() => tokensToCss(badUnit)).toThrow(/space\.bad.*vw/);
  });

  it("rejects a number token that is not a finite number", () => {
    const tokens = base();
    tokens.opacity = { broken: { $type: "number", $value: "0.5" } };
    expect(() => tokensToCss(tokens)).toThrow(/opacity\.broken/);
  });
});

describe("tokensToCss: fonts and type roles", () => {
  const role = (overrides: Dict = {}) => ({
    $type: "typography",
    $value: {
      fontFamily: "{font.family.sans}",
      fontSize: px(25),
      fontWeight: "{font.weight.sans-semibold}",
      letterSpacing: px(-0.3),
      lineHeight: 1.28,
      ...overrides,
    },
  });

  function withTypography(roles: Dict): Dict {
    const tokens = base();
    tokens.font.weight = { "sans-semibold": { $type: "fontWeight", $value: 600 } };
    tokens.typography = roles;
    return tokens;
  }

  it("points --font-sans and --font-mono at the next/font variables, keeping the fallbacks", () => {
    const out = vars(tokensToCss(base()));
    expect(out.get("--font-sans")).toBe("var(--font-overpass), system-ui, sans-serif");
    expect(out.get("--font-mono")).toBe("var(--font-overpass-mono), ui-monospace, monospace");
  });

  it("writes any other family as a font stack, quoting names with spaces", () => {
    const tokens = base();
    tokens.font.family.serif = { $type: "fontFamily", $value: ["Source Serif 4", "Georgia", "serif"] };
    tokens.font.family.single = { $type: "fontFamily", $value: "Inter" };
    const out = vars(tokensToCss(tokens));
    expect(out.get("--font-serif")).toBe('"Source Serif 4", Georgia, serif');
    expect(out.get("--font-single")).toBe("Inter");
  });

  it("names the required font family group when it is missing", () => {
    const tokens = base();
    delete tokens.font;
    expect(() => tokensToCss(tokens)).toThrow("font.family");
  });

  it("rejects an empty font stack", () => {
    const tokens = base();
    tokens.font.family.sans.$value = [];
    expect(() => tokensToCss(tokens)).toThrow(/font\.family\.sans/);
  });

  it("emits font weights as --font-weight variables", () => {
    const tokens = base();
    tokens.font.weight = { "sans-extrabold": { $type: "fontWeight", $value: 800 }, "mono-bold": { $type: "fontWeight", $value: "bold" } };
    const out = vars(tokensToCss(tokens));
    expect(out.get("--font-weight-sans-extrabold")).toBe("800");
    expect(out.get("--font-weight-mono-bold")).toBe("bold");
  });

  it("rejects a font weight outside 1 to 1000", () => {
    const tokens = base();
    tokens.font.weight = { heavy: { $type: "fontWeight", $value: 1200 } };
    expect(() => tokensToCss(tokens)).toThrow(/font\.weight\.heavy/);
  });

  it("splits a type role into five variables with references resolved", () => {
    const out = vars(tokensToCss(withTypography({ "card-statement": role() })));
    expect(out.get("--type-card-statement-family")).toBe("var(--font-sans)");
    expect(out.get("--type-card-statement-size")).toBe("25px");
    expect(out.get("--type-card-statement-weight")).toBe("600");
    expect(out.get("--type-card-statement-line-height")).toBe("1.28");
    expect(out.get("--type-card-statement-letter-spacing")).toBe("-0.3px");
  });

  it("points a mono role at --font-mono", () => {
    const out = vars(tokensToCss(withTypography({ score: role({ fontFamily: "{font.family.mono}" }) })));
    expect(out.get("--type-score-family")).toBe("var(--font-mono)");
  });

  it("writes a role with a literal family and weight as they are", () => {
    const out = vars(tokensToCss(withTypography({ quote: role({ fontFamily: ["Georgia", "serif"], fontWeight: 400 }) })));
    expect(out.get("--type-quote-family")).toBe("Georgia, serif");
    expect(out.get("--type-quote-weight")).toBe("400");
  });

  it("accepts a line height given as a dimension", () => {
    const out = vars(tokensToCss(withTypography({ tight: role({ lineHeight: px(20) }) })));
    expect(out.get("--type-tight-line-height")).toBe("20px");
  });

  it("names the role and the field that is missing", () => {
    const value = role().$value as Dict;
    delete value.letterSpacing;
    expect(() => tokensToCss(withTypography({ stamp: { $type: "typography", $value: value } }))).toThrow(
      /typography\.stamp is missing letterSpacing/,
    );
  });

  it("names the role when its family reference does not exist", () => {
    expect(() => tokensToCss(withTypography({ logo: role({ fontFamily: "{font.family.display}" }) }))).toThrow(
      "typography.logo refers to {font.family.display}, which does not exist",
    );
  });
});

describe("tokensToCss: elevation and motion", () => {
  it("writes a day shadow as a CSS box-shadow list, layers in order", () => {
    const tokens = base();
    tokens.elevation.day.ticket = {
      $type: "shadow",
      $value: [
        { color: srgb("#10233f", 0.06), offsetX: px(0), offsetY: px(1), blur: px(0), spread: px(0) },
        { color: srgb("#10233f", 0.45), offsetX: px(0), offsetY: px(22), blur: px(36), spread: px(-18) },
      ],
    };
    expect(vars(tokensToCss(tokens)).get("--elevation-ticket")).toBe(
      "0px 1px 0px 0px rgb(16 35 63 / 0.06), 0px 22px 36px -18px rgb(16 35 63 / 0.45)",
    );
  });

  it("accepts a single shadow object, an inset layer and a color reference", () => {
    const tokens = base();
    tokens.elevation.day.well = {
      $type: "shadow",
      $value: { color: "{color.primitive.navy-900}", offsetX: px(0), offsetY: px(2), blur: px(4), spread: px(0), inset: true },
    };
    expect(vars(tokensToCss(tokens)).get("--elevation-well")).toBe("inset 0px 2px 4px 0px #10233f");
  });

  it("leaves night elevation out", () => {
    expect(tokensToCss(base())).not.toContain("#000000");
    expect(tokensToCss(base())).not.toContain("rgb(0 0 0");
  });

  it("names a shadow layer that is missing a field", () => {
    const tokens = base();
    tokens.elevation.day.small.$value = [{ color: srgb("#10233f"), offsetX: px(0), offsetY: px(1), spread: px(0) }];
    expect(() => tokensToCss(tokens)).toThrow(/elevation\.day\.small is missing blur/);
  });

  it("emits durations and easing curves", () => {
    const tokens = base();
    tokens.motion.duration.slow = { $type: "duration", $value: { value: 1.5, unit: "s" } };
    const out = vars(tokensToCss(tokens));
    expect(out.get("--duration-t1")).toBe("120ms");
    expect(out.get("--duration-slow")).toBe("1.5s");
    expect(out.get("--easing-ease")).toBe("cubic-bezier(0.2, 0.7, 0.2, 1)");
  });

  it("allows an overshooting curve but rejects x values outside 0 to 1 and wrong lengths", () => {
    const spring = base();
    spring.motion.easing.spring = { $type: "cubicBezier", $value: [0.34, 1.56, 0.64, 1] };
    expect(vars(tokensToCss(spring)).get("--easing-spring")).toBe("cubic-bezier(0.34, 1.56, 0.64, 1)");
    const badX = base();
    badX.motion.easing.bad = { $type: "cubicBezier", $value: [1.2, 0, 0.5, 1] };
    expect(() => tokensToCss(badX)).toThrow(/motion\.easing\.bad/);
    const short = base();
    short.motion.easing.short = { $type: "cubicBezier", $value: [0.2, 0.7, 0.2] };
    expect(() => tokensToCss(short)).toThrow(/motion\.easing\.short/);
  });

  it("names the required duration and easing groups when they are missing", () => {
    const noDuration = base();
    delete noDuration.motion.duration;
    expect(() => tokensToCss(noDuration)).toThrow("motion.duration");
    const noEasing = base();
    delete noEasing.motion.easing;
    expect(() => tokensToCss(noEasing)).toThrow("motion.easing");
    const noElevation = base();
    delete noElevation.elevation.day;
    expect(() => tokensToCss(noElevation)).toThrow("elevation.day");
  });

  it("writes springs and transitions as duration, curve and delay with references resolved", () => {
    const tokens = base();
    tokens.motion.duration.hold = { $type: "duration", $value: ms(60) };
    tokens.motion.spring = {
      snap: { $type: "transition", $value: { duration: "{motion.duration.t1}", delay: ms(0), timingFunction: "{motion.easing.ease}" } },
    };
    tokens.motion.transition = {
      travel: {
        $type: "transition",
        $value: { duration: ms(300), delay: "{motion.duration.hold}", timingFunction: [0, 0, 0.58, 1] },
      },
    };
    const out = vars(tokensToCss(tokens));
    expect(out.get("--spring-snap")).toBe("120ms cubic-bezier(0.2, 0.7, 0.2, 1) 0ms");
    expect(out.get("--transition-travel")).toBe("300ms cubic-bezier(0, 0, 0.58, 1) 60ms");
  });

  it("names a transition whose timing function reference does not exist", () => {
    const tokens = base();
    tokens.motion.transition = {
      press: { $type: "transition", $value: { duration: ms(120), delay: ms(0), timingFunction: "{motion.easing.bounce}" } },
    };
    expect(() => tokensToCss(tokens)).toThrow("motion.transition.press refers to {motion.easing.bounce}, which does not exist");
  });

  it("emits gesture tokens of mixed types", () => {
    const tokens = base();
    tokens.motion.gesture = {
      "commit-distance": { $type: "dimension", $value: px(90) },
      "rotation-divisor": { $type: "number", $value: 18 },
    };
    const out = vars(tokensToCss(tokens));
    expect(out.get("--gesture-commit-distance")).toBe("90px");
    expect(out.get("--gesture-rotation-divisor")).toBe("18");
  });
});
